# Config file for the acts_as_solr plugin.
#
# If you change the host or port number here, make sure you update 
# them in your Solr config file

development:
  url: http://127.0.0.1:8983/solr
  
production:
  #url: http://mysql.corporategray.com:8080/solr
  #url: http://127.0.0.1:8982/solr
  #url: http://data.corporategray.com:8080/solr
  url: http://127.0.0.1:8080/solr

test:
  url: http://127.0.0.1:8983/solr

