source 'http://rubygems.org'

gem "rake", "0.9.2"
gem 'rails', '3.0.9'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

#gem 'sqlite3-ruby', :require => 'sqlite3'

source 'http://gems.github.com'

group :development, :test do 
  gem 'wirble'
end

#gem 'paperclip', "2.3.15", :git => 'git://github.com/thoughtbot/paperclip.git'
gem 'paperclip', "2.3.15"

# gem "exception_notification", :git => "git://github.com/rails/exception_notification", :require => 'exception_notifier'
# gem 'factory_girl', "2.6.4"
# gem 'factory_girl_rails'
# gem 'thoughtbot-shoulda',      :require => 'shoulda'       

gem "will_paginate", "~> 3.0"
gem 'validatable'
gem "daemons", "1.0.10"
gem "delayed_job", "~> 2.1"
gem "mysql2", "= 0.2.10"
gem 'validates_timeliness', '~> 3.0.2'
gem "rubyzip", '< 1.0.0'
gem "json"
gem "omniauth", "~> 0.3.2"
gem "sunspot_rails", '~>1.2.1'
gem "text"

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
