module Constants

  HOME_URL = "/"
	ADMIN_URL = "/admin"


  PAGE_SIZE = 20

  MAX_INBOX_SIZE = 25
  
  # Formats
  EMAIL_PATTERN = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  DATE_PATTERN = /^\d?\d[-\/]\d?\d[-\/](\d\d)?\d\d$/
  TIME_PATTERN = /^[01]?\d:[0-5]\d\s?(am|pm)$/i
  
  DEFAULT_PUBLISH_PERIOD = 30.days

  RELOCATION_COST = [["Paid", 'paid'], ["Partial", "partial"], ["Not Paid", "not_paid"]]
  
  BRANCH_OF_SERVICE = [
    {:id => "0" , :parent => nil, :label => "UNSPECIFIED",          :search_label => nil,           :sort =>  14, :user_select => false},
    {:id => "1" , :parent => nil, :label => "Army",                 :search_label => "Army",        :sort =>  4,  :user_select => true },
    {:id => "10", :parent => 1  , :label => "Army National Guard",  :search_label => nil,           :sort =>  5,  :user_select => true },
    {:id => "12", :parent => 5  , :label => "Coast Guard Reserve",  :search_label => nil,           :sort =>  8,  :user_select => true },
    {:id => "13", :parent => 3  , :label => "Air National Guard",   :search_label => nil,           :sort =>  3,  :user_select => true },
    {:id => "14", :parent => nil, :label => "Other",                :search_label => "Other",       :sort =>  13, :user_select => true },
    {:id => "2" , :parent => nil, :label => "Navy",                 :search_label => "Navy",        :sort =>  11, :user_select => true },
    {:id => "3" , :parent => nil, :label => "Air Force",            :search_label => "Air Force",   :sort =>  1,  :user_select => true },
    {:id => "4" , :parent => nil, :label => "Marine Corps",         :search_label => "Marine Corps",:sort =>  9,  :user_select => true },
    {:id => "5" , :parent => nil, :label => "Coast Guard",          :search_label => "Coast Guard", :sort =>  7,  :user_select => true },
    {:id => "6" , :parent => 1  , :label => "Army Reserve",         :search_label => nil,           :sort =>  6,  :user_select => true },
    {:id => "7" , :parent => 2  , :label => "Navy Reserve",         :search_label => nil,           :sort =>  12, :user_select => true },
    {:id => "8" , :parent => 3  , :label => "Air Force Reserve",    :search_label => nil,           :sort =>  2,  :user_select => true },
    {:id => "9" , :parent => 4  , :label => "Marine Corps Reserve", :search_label => nil,           :sort =>  10, :user_select => true }
  ]
  
  EDUCATION_LEVEL = [
    {:id => "0", :parent => nil, :label => "UNSPECIFIED",                 :search_label => nil,                           :sort => 5, :user_select => false},
    {:id => "1", :parent => nil, :label => "High School or GED",           :search_label => "High School-GED",           :sort => 1, :user_select => true },
    {:id => "3", :parent => nil, :label => "Associates Degree",           :search_label => "Associates Degree",           :sort => 3, :user_select => true },
    {:id => "4", :parent => nil, :label => "Bachelors Degree or Higher", :search_label => "Bachelors Degree or Higher",  :sort => 4, :user_select => true }
  ]
  
  MILITARY_STATUS = [
    {:id => "0"  , :parent => nil, :label => "UNSPECIFIED", :search_label => nil, :sort => 5, :user_select => false },
    {:id => "ACT", :parent => nil, :label => "Active",      :search_label => nil, :sort => 1, :user_select => true  },
    {:id => "RES", :parent => nil, :label => "Reserve",     :search_label => nil, :sort => 2, :user_select => true  },
    {:id => "RET", :parent => nil, :label => "Retired",     :search_label => nil, :sort => 4, :user_select => true  },
    {:id => "SEP", :parent => nil, :label => "Separated",   :search_label => nil, :sort => 3, :user_select => true  }
  ]
  
  OCCUPATIONAL_PREFERENCE = [
    {:id => "0",  :parent => nil, :label => "UNSPECIFIED",		:search_label => nil, :sort => 76, :user_select => false},
    {:id => "0Q", :parent => nil, :label => "Civil Engineering",	:search_label => nil, :sort => 65, :user_select => true},
    {:id => "0S", :parent => nil, :label => "General Engineering",	:search_label => nil, :sort => 67, :user_select => true},
    {:id => "24", :parent => nil, :label => "Forestry",			:search_label => nil, :sort => 24, :user_select => true},
    {:id => "26", :parent => nil, :label => "Religion",			:search_label => nil, :sort => 46, :user_select => true},
    {:id => "3C", :parent => nil, :label => "Aeronautical Engineering",	:search_label => nil, :sort => 63, :user_select => true},
    {:id => "3I", :parent => nil, :label => "Telemarketing",		:search_label => nil, :sort => 56, :user_select => true},
    {:id => "3S", :parent => nil, :label => "Customer Service",		:search_label => nil, :sort => 14, :user_select => true},
    {:id => "5A", :parent => nil, :label => "Food Service",		:search_label => nil, :sort => 23, :user_select => true},
    {:id => "6X", :parent => nil, :label => "Equipment Maintenance",	:search_label => nil, :sort => 20, :user_select => true},
    {:id => "74", :parent => nil, :label => "Technical Services",	:search_label => nil, :sort => 53, :user_select => true},
    {:id => "79", :parent => nil, :label => "Insurance",		:search_label => nil, :sort => 30, :user_select => true},
    {:id => "7A", :parent => nil, :label => "Automotive",		:search_label => nil, :sort => 6,  :user_select => true},
    {:id => "7L", :parent => nil, :label => "Telecommunications",	:search_label => nil, :sort => 55, :user_select => true},
    {:id => "82", :parent => nil, :label => "Systems Engineering",	:search_label => nil, :sort => 75, :user_select => true},
    {:id => "88", :parent => nil, :label => "Real Estate/Property Management",	:search_label => nil, :sort => 44, :user_select => true},
    {:id => "9K", :parent => nil, :label => "Purchasing/Contracts",	:search_label => nil, :sort => 43, :user_select => true},
    {:id => "9Y", :parent => nil, :label => "Agriculture",		:search_label => nil, :sort => 4,  :user_select => true},
    {:id => "A5", :parent => nil, :label => "Materials/Metallurgical Engineering",	:search_label => nil, :sort => 70, :user_select => true},
    {:id => "A7", :parent => nil, :label => "Healthcare/Medical",	:search_label => nil, :sort => 26, :user_select => true},
    {:id => "AT", :parent => nil, :label => "Non-Profit",		:search_label => nil, :sort => 38, :user_select => true},
    {:id => "B0", :parent => nil, :label => "Consulting",		:search_label => nil, :sort => 12, :user_select => true},
    {:id => "C4", :parent => nil, :label => "Security",			:search_label => nil, :sort => 50, :user_select => true},
    {:id => "CD", :parent => nil, :label => "Legal Services",		:search_label => nil, :sort => 33, :user_select => true},
    {:id => "CG", :parent => nil, :label => "Textile",			:search_label => nil, :sort => 57, :user_select => true},
    {:id => "CO", :parent => nil, :label => "Advertising",		:search_label => nil, :sort => 3,  :user_select => true},
    {:id => "D2", :parent => nil, :label => "Warehouse",		:search_label => nil, :sort => 62, :user_select => true},
    {:id => "D3", :parent => nil, :label => "Child Care",		:search_label => nil, :sort => 10, :user_select => true},
    {:id => "DK", :parent => nil, :label => "Administrative",		:search_label => nil, :sort => 2,  :user_select => true},
    {:id => "DM", :parent => nil, :label => "Logistics/Maintenance",	:search_label => nil, :sort => 35, :user_select => true},
    {:id => "DP", :parent => nil, :label => "Linguistics",		:search_label => nil, :sort => 34, :user_select => true},
    {:id => "ES", :parent => nil, :label => "Education/Teaching",	:search_label => nil, :sort => 17, :user_select => true},
    {:id => "ET", :parent => nil, :label => "Air Conditioning/HVAC",	:search_label => nil, :sort => 5,  :user_select => true},
    {:id => "FL", :parent => nil, :label => "Law Enforcement/Security",	:search_label => nil, :sort => 32, :user_select => true},
    {:id => "G1", :parent => nil, :label => "Quality Assurance",	:search_label => nil, :sort => 73, :user_select => true},
    {:id => "GS", :parent => nil, :label => "Information Technology",	:search_label => nil, :sort => 29, :user_select => true},
    {:id => "HF", :parent => nil, :label => "Janitorial/Custodial",	:search_label => nil, :sort => 31, :user_select => true},
    {:id => "IC", :parent => nil, :label => "Social Services",		:search_label => nil, :sort => 52, :user_select => true},
    {:id => "IE", :parent => nil, :label => "Chemicals",		:search_label => nil, :sort => 9,  :user_select => true},
    {:id => "JZ", :parent => nil, :label => "Environmental Engineering",:search_label => nil, :sort => 66, :user_select => true},
    {:id => "K4", :parent => nil, :label => "Accounting",		:search_label => nil, :sort => 1,  :user_select => true},
    {:id => "KE", :parent => nil, :label => "Government",		:search_label => nil, :sort => 25, :user_select => true},
    {:id => "KL", :parent => nil, :label => "Recreation",		:search_label => nil, :sort => 45, :user_select => true},
    {:id => "KY", :parent => nil, :label => "Utilities",		:search_label => nil, :sort => 60, :user_select => true},
    {:id => "LP", :parent => nil, :label => "Marine Engineering",	:search_label => nil, :sort => 69, :user_select => true},
    {:id => "MG", :parent => nil, :label => "Mechanical Engineering",	:search_label => nil, :sort => 71, :user_select => true},
    {:id => "MI", :parent => nil, :label => "Manufacturing",		:search_label => nil, :sort => 36, :user_select => true},
    {:id => "MM", :parent => nil, :label => "Environmental",		:search_label => nil, :sort => 19, :user_select => true},
    {:id => "MQ", :parent => nil, :label => "Transportation Services",	:search_label => nil, :sort => 59, :user_select => true},
    {:id => "N5", :parent => nil, :label => "Software Engineering",	:search_label => nil, :sort => 74, :user_select => true},
    {:id => "N7", :parent => nil, :label => "Sales and Marketing",	:search_label => nil, :sort => 49, :user_select => true},
    {:id => "NE", :parent => nil, :label => "Training",			:search_label => nil, :sort => 58, :user_select => true},
    {:id => "NM", :parent => nil, :label => "Banking",			:search_label => nil, :sort => 8,  :user_select => true},
    {:id => "NV", :parent => nil, :label => "Technical Writing",	:search_label => nil, :sort => 54, :user_select => true},
    {:id => "O8", :parent => nil, :label => "Hospitality/Lodging",	:search_label => nil, :sort => 27, :user_select => true},
    {:id => "OU", :parent => nil, :label => "Shipping",			:search_label => nil, :sort => 51, :user_select => true},
    {:id => "P1", :parent => nil, :label => "Drivers",			:search_label => nil, :sort => 16, :user_select => true},
    {:id => "QD", :parent => nil, :label => "Construction",		:search_label => nil, :sort => 11, :user_select => true},
    {:id => "S1", :parent => nil, :label => "Nuclear Engineering",	:search_label => nil, :sort => 72, :user_select => true},
    {:id => "S9", :parent => nil, :label => "Retail",			:search_label => nil, :sort => 48, :user_select => true},
    {:id => "SA", :parent => nil, :label => "Mining",			:search_label => nil, :sort => 37, :user_select => true},
    {:id => "T8", :parent => nil, :label => "Public Relations",		:search_label => nil, :sort => 42, :user_select => true},
    {:id => "U4", :parent => nil, :label => "Industrial Engineering",	:search_label => nil, :sort => 68, :user_select => true},
    {:id => "UH", :parent => nil, :label => "Chemical Engineering",	:search_label => nil, :sort => 64, :user_select => true},
    {:id => "VA", :parent => nil, :label => "Veterinary",		:search_label => nil, :sort => 61, :user_select => true},
    {:id => "VD", :parent => nil, :label => "Human Resources",		:search_label => nil, :sort => 28, :user_select => true},
    {:id => "VV", :parent => nil, :label => "Aviation",			:search_label => nil, :sort => 7,  :user_select => true},
    {:id => "W8", :parent => nil, :label => "Counseling",		:search_label => nil, :sort => 13, :user_select => true},
    {:id => "WN", :parent => nil, :label => "Nuclear",			:search_label => nil, :sort => 39, :user_select => true},
    {:id => "X6", :parent => nil, :label => "Oil/Petroleum",		:search_label => nil, :sort => 40, :user_select => true},
    {:id => "X8", :parent => nil, :label => "Financial Services",	:search_label => nil, :sort => 22, :user_select => true},
    {:id => "XF", :parent => nil, :label => "Defense",			:search_label => nil, :sort => 15, :user_select => true},
    {:id => "Y1", :parent => nil, :label => "Facilities Management",	:search_label => nil, :sort => 21, :user_select => true},
    {:id => "YS", :parent => nil, :label => "Pharmaceuticals",		:search_label => nil, :sort => 41, :user_select => true},
    {:id => "Z6", :parent => nil, :label => "Research/Scientific",	:search_label => nil, :sort => 47, :user_select => true}
  ]
  
  PAY_RATE = [
    { :id =>  "0",  :parent => nil, :label => "UNSPECIFIED",                  :search_label => nil, :sort =>  8, :user_select => false},
    { :id =>  "1",  :parent => nil, :label => "Less than $20,000",            :search_label => nil, :sort =>  2, :user_select => true },
    { :id =>  "10", :parent => nil, :label => "Commensurate with experience", :search_label => nil, :sort =>  1,:user_select => true },
    { :id =>  "2",  :parent => nil, :label => "$20,000 to $40,000",           :search_label => nil, :sort =>  3, :user_select => true },
    { :id =>  "4",  :parent => nil, :label => "$40,000 to $60,000",           :search_label => nil, :sort =>  4, :user_select => true },
    { :id =>  "6",  :parent => nil, :label => "$60,000 to $80,000",           :search_label => nil, :sort =>  5, :user_select => true },
    { :id =>  "8",  :parent => nil, :label => "$80,000 to $100,000",          :search_label => nil, :sort =>  6, :user_select => true },
    { :id =>  "9",  :parent => nil, :label => "Over $100,000",                :search_label => nil, :sort =>  7, :user_select => true }
  ]
  
  SECURITY_CLEARANCE = [
    {:id => "0", :parent => nil,  :label => "UNSPECIFIED",          :search_label => nil, :sort => 6, :user_select => false}, 
    {:id => "1", :parent => nil,  :label => "Secret",               :search_label => nil, :sort => 2, :user_select => true }, 
    {:id => "2", :parent => 1,    :label => "Top Secret",           :search_label => nil, :sort => 3, :user_select => true }, 
    {:id => "3", :parent => nil,  :label => "None",                 :search_label => nil, :sort => 1, :user_select => true }, 
    {:id => "4", :parent => nil,  :label => "Secret or Top Secret", :search_label => nil, :sort => 4, :user_select => false }
  ]
  
  TIME_PERIOD = [
    { :id => "0", :parent => nil, :label => " UNSPECIFIED", :search_label => nil, :sort => 7, :user_select => false},
    { :id => "B", :parent => nil, :label => " By-weekly",   :search_label => nil, :sort => 3, :user_select => true },
    { :id => "D", :parent => nil, :label => " Daily",       :search_label => nil, :sort => 5, :user_select => true },
    { :id => "H", :parent => nil, :label => " Houlry",      :search_label => nil, :sort => 6, :user_select => true },
    { :id => "M", :parent => nil, :label => " Montly",      :search_label => nil, :sort => 2, :user_select => true },
    { :id => "W", :parent => nil, :label => " Weekly",      :search_label => nil, :sort => 4, :user_select => true },
    { :id => "Y", :parent => nil, :label => " Yearly",      :search_label => nil, :sort => 1, :user_select => true }
  ]
  
  TRAVEL_REQUIREMENT = [
    { :id => "0",   :parent => nil, :label => "UNSPECIFIED",  :search_label => nil, :sort => 5, :user_select => false},
    { :id => "HEAVY", :parent => nil, :label => "Heavy",      :search_label => nil, :sort => 4, :user_select => true },
    { :id => "LIGHT", :parent => nil, :label => "Light",      :search_label => nil, :sort => 2, :user_select => true },
    { :id => "MODTR", :parent => nil, :label => "Moderate",   :search_label => nil, :sort => 3, :user_select => true },
    { :id => "NONE",  :parent => nil, :label => "None",       :search_label => nil, :sort => 1, :user_select => true }
  ]

  TYPE_OF_APPLICANT = [
    { :id => "0",  :parent => nil, :label => "UNSPECIFIED",                                         :search_label => nil,                                                   :sort =>  27, :user_select => false},
    { :id => "10", :parent => nil, :label => "O-7 / Brigadier General or Commodore",                :search_label => "O-7 / Brigadier General or Commodore",                :sort =>  16, :user_select => true },
    { :id => "11", :parent => nil, :label => "O-9 / Lieutenant General or Vice Admiral",            :search_label => "O-9 / Lieutenant General or Vice Admiral",            :sort =>  18, :user_select => true },
    { :id => "12", :parent => nil, :label => "O-8 / Major General or Rear Admiral",                 :search_label => "O-8 / Major General or Rear Admiral",                 :sort =>  17, :user_select => true },
    { :id => "13", :parent => nil, :label => "O-1 / 2nd Lieutenant or Ensign",                      :search_label => "O-1 / 2nd Lieutenant or Ensign",                      :sort =>  10, :user_select => true },
    { :id => "16", :parent => nil, :label => "W-1/Warrant Officer",                                 :search_label => "W-1/Warrant Officer",                                 :sort =>  20, :user_select => true },
    { :id => "22", :parent => nil, :label => "E-2 / Private or Seaman Apprentice",                  :search_label => "E-2 / Private or Seaman Apprentice",                  :sort =>  2,  :user_select => true },
    { :id => "23", :parent => nil, :label => "E-3 / Private First Class or Seaman",                 :search_label => "E-3 / Private First Class or Seaman",                 :sort =>  3,  :user_select => true },
    { :id => "24", :parent => nil, :label => "E-4 / Corporal or Petty Officer 3rd Class",           :search_label => "E-4 / Corporal or Petty Officer 3rd Class",           :sort =>  4,  :user_select => true },
    { :id => "25", :parent => nil, :label => "E-5 / Sergeant or Petty Officer 2nd Class",           :search_label => "E-5 / Sergeant or Petty Officer 2nd Class",           :sort =>  5,  :user_select => true },
    { :id => "26", :parent => nil, :label => "E-6 / Staff Sergeant or Petty Officer 1st Class",     :search_label => "E-6 / Staff Sergeant or Petty Officer 1st Class",     :sort =>  6,  :user_select => true },
    { :id => "27", :parent => nil, :label => "E-7 / Sergeant First Class or Chief Petty Officer",   :search_label => "E-7 / Sergeant First Class or Chief Petty Officer",   :sort =>  7,  :user_select => true },
    { :id => "28", :parent => nil, :label => "E-8 / Master Sergeant or Senior Chief Petty Officer", :search_label => "E-8 / Master Sergeant or Senior Chief Petty Officer", :sort =>  8,  :user_select => true },
    { :id => "29", :parent => nil, :label => "E-9 / Sergeant Major or Master Chief Petty Officer",  :search_label => "E-9 / Sergeant Major or Master Chief Petty Officer",  :sort =>  9,  :user_select => true },
    { :id => "3",  :parent => nil, :label => "E-1 / Private or Seaman Recruit",                     :search_label => "E-1 / Private or Seaman Recruit",                     :sort =>  1,  :user_select => true },
    { :id => "30", :parent => nil, :label => "Military Spouse",                                     :search_label => "Military Spouse",                                     :sort =>  25, :user_select => true },
    { :id => "31", :parent => nil, :label => "W-2/Chief Warrant Officer",                           :search_label => "W-2/Chief Warrant Officer",                           :sort =>  21, :user_select => true },
    { :id => "32", :parent => nil, :label => "W-3/Senior Chief Warrant Officer",                    :search_label => "W-3/Senior Chief Warrant Officer",                    :sort =>  22, :user_select => true },
    { :id => "33", :parent => nil, :label => "W-4/Master Chief Warrant Officer",                    :search_label => "W-4/Master Chief Warrant Officer",                    :sort =>  23, :user_select => true },
    { :id => "34", :parent => nil, :label => "W-5/Senior Master Chief Warrant Officer",             :search_label => "W-5/Senior Master Chief Warrant Officer",             :sort =>  24, :user_select => true },
    { :id => "35", :parent => nil, :label => "O-10 / General or Admiral",                           :search_label => "O-10 / General or Admiral",                           :sort =>  19, :user_select => true },
    { :id => "37", :parent => nil, :label => "Civilian",                                            :search_label => "Civilian",                                            :sort =>  26, :user_select => true },
    { :id => "5",  :parent => nil, :label => "O-2 / 1st Lieutenant or Lieutenant jg",               :search_label => "O-2 / 1st Lieutenant or Lieutenant jg",               :sort =>  11, :user_select => true },
    { :id => "6",  :parent => nil, :label => "O-3 / Captain or Navy Lieutenant",                    :search_label => "O-3 / Captain or Navy Lieutenant",                    :sort =>  12, :user_select => true },
    { :id => "7",  :parent => nil, :label => "O-4 / Major or Lieutenant Commander",                 :search_label => "O-4 / Major or Lieutenant Commander",                 :sort =>  13, :user_select => true },
    { :id => "8",  :parent => nil, :label => "O-5 / Lieutenant Colonel or Commander",               :search_label => "O-5 / Lieutenant Colonel or Commander",               :sort =>  14, :user_select => true },
    { :id => "9",  :parent => nil, :label => "O-6 / Colonel or Navy Captain",                       :search_label => "O-6 / Colonel or Navy Captain",                       :sort =>  15, :user_select => true }
  ]
  
  # [DisplayName, Value]
  GENDER = [["Male", "male"], ["Female", "female"]]
  
  # [DisplayName, Value]
  ETHNICITY = [
    ["Not Specified", "not_specified"],
    ["White", "white"], 
    ["Black", "black"],
    ["Asian", "asian"],
    ["Hispanic", "hispanic"],
    ["American Indian or Alaska Native", "american_indian_or_alaska_native"]
  ]
  
  
  
  
  
  COUNTRIES = [
    {:id =>"0", :parent => nil, :label => "UNSPECIFIED", :search_label => nil, :sort => 289, :user_select => true},
    {:id =>"001", :parent => nil, :label => "Algeria", :search_label => nil, :sort => 4, :user_select => true},
    {:id =>"002", :parent => nil, :label => "Angola", :search_label => nil, :sort => 7, :user_select => true},
    {:id =>"003", :parent => nil, :label => "Anguilla", :search_label => nil, :sort => 8, :user_select => true},
    {:id =>"004", :parent => nil, :label => "Antigua", :search_label => nil, :sort => 10, :user_select => true},
    {:id =>"005", :parent => nil, :label => "Argentina", :search_label => nil, :sort => 12, :user_select => true},
    {:id =>"006", :parent => nil, :label => "Aruba", :search_label => nil, :sort => 14, :user_select => true},
    {:id =>"007", :parent => nil, :label => "Australia", :search_label => nil, :sort => 15, :user_select => true},
    {:id =>"008", :parent => nil, :label => "Austria", :search_label => nil, :sort => 16, :user_select => true},
    {:id =>"009", :parent => nil, :label => "Bahamas", :search_label => nil, :sort => 19, :user_select => true},
    {:id =>"010", :parent => nil, :label => "Bahrain", :search_label => nil, :sort => 20, :user_select => true},
    {:id =>"011", :parent => nil, :label => "Bangladesh", :search_label => nil, :sort => 21, :user_select => true},
    {:id =>"012", :parent => nil, :label => "Barbados", :search_label => nil, :sort => 22, :user_select => true},
    {:id =>"013", :parent => nil, :label => "Barbuda", :search_label => nil, :sort => 23, :user_select => true},
    {:id =>"014", :parent => nil, :label => "Belorus", :search_label => nil, :sort => 26, :user_select => true},
    {:id =>"015", :parent => nil, :label => "Belgium", :search_label => nil, :sort => 24, :user_select => true},
    {:id =>"016", :parent => nil, :label => "Belize", :search_label => nil, :sort => 25, :user_select => true},
    {:id =>"017", :parent => nil, :label => "Benin", :search_label => nil, :sort => 27, :user_select => true},
    {:id =>"018", :parent => nil, :label => "Bermuda", :search_label => nil, :sort => 28, :user_select => true},
    {:id =>"019", :parent => nil, :label => "Bhutan", :search_label => nil, :sort => 29, :user_select => true},
    {:id =>"020", :parent => nil, :label => "Bolivia", :search_label => nil, :sort => 30, :user_select => true},
    {:id =>"021", :parent => nil, :label => "Bonaire", :search_label => nil, :sort => 31, :user_select => true},
    {:id =>"022", :parent => nil, :label => "Botswana", :search_label => nil, :sort => 33, :user_select => true},
    {:id =>"023", :parent => nil, :label => "Brazil", :search_label => nil, :sort => 36, :user_select => true},
    {:id =>"024", :parent => nil, :label => "Br. Virgin Islands", :search_label => nil, :sort => 35, :user_select => true},
    {:id =>"025", :parent => nil, :label => "Brunei", :search_label => nil, :sort => 38, :user_select => true},
    {:id =>"026", :parent => nil, :label => "Bulgaria", :search_label => nil, :sort => 39, :user_select => true},
    {:id =>"027", :parent => nil, :label => "Burkina Faso", :search_label => nil, :sort => 40, :user_select => true},
    {:id =>"028", :parent => nil, :label => "Burundi", :search_label => nil, :sort => 41, :user_select => true},
    {:id =>"029", :parent => nil, :label => "Cameroon", :search_label => nil, :sort => 44, :user_select => true},
    {:id =>"030", :parent => nil, :label => "Canada", :search_label => nil, :sort => 45, :user_select => true},
    {:id =>"031", :parent => nil, :label => "Cape Verde", :search_label => nil, :sort => 47, :user_select => true},
    {:id =>"032", :parent => nil, :label => "Cayman Islands", :search_label => nil, :sort => 48, :user_select => true},
    {:id =>"033", :parent => nil, :label => "Central African Republic", :search_label => nil, :sort => 49, :user_select => true},
    {:id =>"034", :parent => nil, :label => "Chad", :search_label => nil, :sort => 50, :user_select => true},
    {:id =>"035", :parent => nil, :label => "Channel Islands", :search_label => nil, :sort => 51, :user_select => true},
    {:id =>"036", :parent => nil, :label => "Chile", :search_label => nil, :sort => 52, :user_select => true},
    {:id =>"037", :parent => nil, :label => "China", :search_label => nil, :sort => 53, :user_select => true},
    {:id =>"038", :parent => nil, :label => "Colombia", :search_label => nil, :sort => 56, :user_select => true},
    {:id =>"039", :parent => nil, :label => "Congo", :search_label => nil, :sort => 59, :user_select => true},
    {:id =>"040", :parent => nil, :label => "Costa Rica", :search_label => nil, :sort => 62, :user_select => true},
    {:id =>"041", :parent => nil, :label => "Curacao", :search_label => nil, :sort => 66, :user_select => true},
    {:id =>"042", :parent => nil, :label => "Cyprus", :search_label => nil, :sort => 67, :user_select => true},
    {:id =>"043", :parent => nil, :label => "Czech Republic", :search_label => nil, :sort => 68, :user_select => true},
    {:id =>"044", :parent => nil, :label => "Denmark", :search_label => nil, :sort => 69, :user_select => true},
    {:id =>"045", :parent => nil, :label => "Djibouti", :search_label => nil, :sort => 70, :user_select => true},
    {:id =>"046", :parent => nil, :label => "Dominica", :search_label => nil, :sort => 71, :user_select => true},
    {:id =>"047", :parent => nil, :label => "Dominican Republic", :search_label => nil, :sort => 72, :user_select => true},
    {:id =>"048", :parent => nil, :label => "Ecuador", :search_label => nil, :sort => 74, :user_select => true},
    {:id =>"049", :parent => nil, :label => "Egypt", :search_label => nil, :sort => 75, :user_select => true},
    {:id =>"050", :parent => nil, :label => "El Salvador", :search_label => nil, :sort => 76, :user_select => true},
    {:id =>"051", :parent => nil, :label => "England", :search_label => nil, :sort => 77, :user_select => true},
    {:id =>"052", :parent => nil, :label => "Equatorial Guinea", :search_label => nil, :sort => 78, :user_select => true},
    {:id =>"053", :parent => nil, :label => "Estonia", :search_label => nil, :sort => 80, :user_select => true},
    {:id =>"054", :parent => nil, :label => "Ethiopia", :search_label => nil, :sort => 81, :user_select => true},
    {:id =>"055", :parent => nil, :label => "Fiji", :search_label => nil, :sort => 84, :user_select => true},
    {:id =>"056", :parent => nil, :label => "Finland", :search_label => nil, :sort => 85, :user_select => true},
    {:id =>"057", :parent => nil, :label => "France", :search_label => nil, :sort => 86, :user_select => true},
    {:id =>"058", :parent => nil, :label => "French Guiana", :search_label => nil, :sort => 87, :user_select => true},
    {:id =>"059", :parent => nil, :label => "Gabon", :search_label => nil, :sort => 91, :user_select => true},
    {:id =>"060", :parent => nil, :label => "Gambia", :search_label => nil, :sort => 92, :user_select => true},
    {:id =>"061", :parent => nil, :label => "Germany", :search_label => nil, :sort => 94, :user_select => true},
    {:id =>"062", :parent => nil, :label => "Ghana", :search_label => nil, :sort => 95, :user_select => true},
    {:id =>"063", :parent => nil, :label => "Greece", :search_label => nil, :sort => 97, :user_select => true},
    {:id =>"064", :parent => nil, :label => "Grenada", :search_label => nil, :sort => 99, :user_select => true},
    {:id =>"065", :parent => nil, :label => "Guadeloupe", :search_label => nil, :sort => 100, :user_select => true},
    {:id =>"066", :parent => nil, :label => "Guam", :search_label => nil, :sort => 101, :user_select => true},
    {:id =>"067", :parent => nil, :label => "Guatemala", :search_label => nil, :sort => 102, :user_select => true},
    {:id =>"068", :parent => nil, :label => "Guinea", :search_label => nil, :sort => 103, :user_select => true},
    {:id =>"069", :parent => nil, :label => "Guinea-Bissau", :search_label => nil, :sort => 104, :user_select => true},
    {:id =>"070", :parent => nil, :label => "Guyana", :search_label => nil, :sort => 105, :user_select => true},
    {:id =>"071", :parent => nil, :label => "Honduras", :search_label => nil, :sort => 109, :user_select => true},
    {:id =>"072", :parent => nil, :label => "Hong Kong", :search_label => nil, :sort => 110, :user_select => true},
    {:id =>"073", :parent => nil, :label => "Hungary", :search_label => nil, :sort => 111, :user_select => true},
    {:id =>"074", :parent => nil, :label => "Iceland", :search_label => nil, :sort => 112, :user_select => true},
    {:id =>"075", :parent => nil, :label => "India", :search_label => nil, :sort => 113, :user_select => true},
    {:id =>"076", :parent => nil, :label => "Indonesia", :search_label => nil, :sort => 114, :user_select => true},
    {:id =>"077", :parent => nil, :label => "Iran", :search_label => nil, :sort => 115, :user_select => true},
    {:id =>"078", :parent => nil, :label => "Ireland, Northern", :search_label => nil, :sort => 117, :user_select => true},
    {:id =>"079", :parent => nil, :label => "Ireland, Republic of", :search_label => nil, :sort => 118, :user_select => true},
    {:id =>"080", :parent => nil, :label => "Israel", :search_label => nil, :sort => 120, :user_select => true},
    {:id =>"081", :parent => nil, :label => "Italy", :search_label => nil, :sort => 121, :user_select => true},
    {:id =>"082", :parent => nil, :label => "Ivory Coast", :search_label => nil, :sort => 122, :user_select => true},
    {:id =>"083", :parent => nil, :label => "Jamaica", :search_label => nil, :sort => 123, :user_select => true},
    {:id =>"084", :parent => nil, :label => "Japan", :search_label => nil, :sort => 124, :user_select => true},
    {:id =>"085", :parent => nil, :label => "Jordan", :search_label => nil, :sort => 125, :user_select => true},
    {:id =>"086", :parent => nil, :label => "Kenya", :search_label => nil, :sort => 129, :user_select => true},
    {:id =>"087", :parent => nil, :label => "Korea, South", :search_label => nil, :sort => 132, :user_select => true},
    {:id =>"088", :parent => nil, :label => "Kuwait", :search_label => nil, :sort => 134, :user_select => true},
    {:id =>"089", :parent => nil, :label => "Latvia", :search_label => nil, :sort => 137, :user_select => true},
    {:id =>"090", :parent => nil, :label => "Lebanon", :search_label => nil, :sort => 138, :user_select => true},
    {:id =>"091", :parent => nil, :label => "Lesotho", :search_label => nil, :sort => 139, :user_select => true},
    {:id =>"092", :parent => nil, :label => "Liechtenstein", :search_label => nil, :sort => 142, :user_select => true},
    {:id =>"093", :parent => nil, :label => "Lithuania", :search_label => nil, :sort => 143, :user_select => true},
    {:id =>"094", :parent => nil, :label => "Luxembourg", :search_label => nil, :sort => 144, :user_select => true},
    {:id =>"095", :parent => nil, :label => "Macau", :search_label => nil, :sort => 145, :user_select => true},
    {:id =>"096", :parent => nil, :label => "Madagascar", :search_label => nil, :sort => 147, :user_select => true},
    {:id =>"097", :parent => nil, :label => "Malawi", :search_label => nil, :sort => 150, :user_select => true},
    {:id =>"098", :parent => nil, :label => "Malaysia", :search_label => nil, :sort => 151, :user_select => true},
    {:id =>"099", :parent => nil, :label => "Maldives", :search_label => nil, :sort => 152, :user_select => true},
    {:id =>"100", :parent => nil, :label => "Mali", :search_label => nil, :sort => 153, :user_select => true},
    {:id =>"101", :parent => nil, :label => "Malta", :search_label => nil, :sort => 154, :user_select => true},
    {:id =>"102", :parent => nil, :label => "Marshall Islands", :search_label => nil, :sort => 155, :user_select => true},
    {:id =>"103", :parent => nil, :label => "Martinique", :search_label => nil, :sort => 156, :user_select => true},
    {:id =>"104", :parent => nil, :label => "Mauritania", :search_label => nil, :sort => 157, :user_select => true},
    {:id =>"105", :parent => nil, :label => "Mauritius", :search_label => nil, :sort => 158, :user_select => true},
    {:id =>"106", :parent => nil, :label => "Mexico", :search_label => nil, :sort => 160, :user_select => true},
    {:id =>"107", :parent => nil, :label => "Micronesia", :search_label => nil, :sort => 161, :user_select => true},
    {:id =>"108", :parent => nil, :label => "Monaco", :search_label => nil, :sort => 163, :user_select => true},
    {:id =>"109", :parent => nil, :label => "Montserrat", :search_label => nil, :sort => 165, :user_select => true},
    {:id =>"110", :parent => nil, :label => "Morocco", :search_label => nil, :sort => 166, :user_select => true},
    {:id =>"111", :parent => nil, :label => "Mozambique", :search_label => nil, :sort => 167, :user_select => true},
    {:id =>"112", :parent => nil, :label => "Namibia", :search_label => nil, :sort => 169, :user_select => true},
    {:id =>"113", :parent => nil, :label => "Nepal", :search_label => nil, :sort => 171, :user_select => true},
    {:id =>"114", :parent => nil, :label => "Netherlands", :search_label => nil, :sort => 172, :user_select => true},
    {:id =>"115", :parent => nil, :label => "Antilles", :search_label => nil, :sort => 11, :user_select => true},
    {:id =>"116", :parent => nil, :label => "New Caledonia", :search_label => nil, :sort => 175, :user_select => true},
    {:id =>"117", :parent => nil, :label => "New Zealand", :search_label => nil, :sort => 176, :user_select => true},
    {:id =>"118", :parent => nil, :label => "Nicaragua", :search_label => nil, :sort => 177, :user_select => true},
    {:id =>"119", :parent => nil, :label => "Niger", :search_label => nil, :sort => 178, :user_select => true},
    {:id =>"120", :parent => nil, :label => "Nigeria", :search_label => nil, :sort => 179, :user_select => true},
    {:id =>"121", :parent => nil, :label => "Norway", :search_label => nil, :sort => 185, :user_select => true},
    {:id =>"122", :parent => nil, :label => "Oman", :search_label => nil, :sort => 186, :user_select => true},
    {:id =>"123", :parent => nil, :label => "Pakistan", :search_label => nil, :sort => 187, :user_select => true},
    {:id =>"124", :parent => nil, :label => "Palau", :search_label => nil, :sort => 188, :user_select => true},
    {:id =>"125", :parent => nil, :label => "Panama", :search_label => nil, :sort => 189, :user_select => true},
    {:id =>"126", :parent => nil, :label => "Papua New Guinea", :search_label => nil, :sort => 190, :user_select => true},
    {:id =>"127", :parent => nil, :label => "Paraguay", :search_label => nil, :sort => 191, :user_select => true},
    {:id =>"128", :parent => nil, :label => "Peru", :search_label => nil, :sort => 192, :user_select => true},
    {:id =>"129", :parent => nil, :label => "Philippines", :search_label => nil, :sort => 193, :user_select => true},
    {:id =>"130", :parent => nil, :label => "Poland", :search_label => nil, :sort => 195, :user_select => true},
    {:id =>"131", :parent => nil, :label => "Portugal", :search_label => nil, :sort => 197, :user_select => true},
    {:id =>"132", :parent => nil, :label => "Qatar", :search_label => nil, :sort => 199, :user_select => true},
    {:id =>"133", :parent => nil, :label => "Reunion", :search_label => nil, :sort => 200, :user_select => true},
    {:id =>"134", :parent => nil, :label => "Romania", :search_label => nil, :sort => 201, :user_select => true},
    {:id =>"135", :parent => nil, :label => "Russia", :search_label => nil, :sort => 203, :user_select => true},
    {:id =>"136", :parent => nil, :label => "Rwanda", :search_label => nil, :sort => 204, :user_select => true},
    {:id =>"137", :parent => nil, :label => "Saba", :search_label => nil, :sort => 206, :user_select => true},
    {:id =>"138", :parent => nil, :label => "St. Barthelemy", :search_label => nil, :sort => 226, :user_select => true},
    {:id =>"139", :parent => nil, :label => "St. Croix", :search_label => nil, :sort => 229, :user_select => true},
    {:id =>"140", :parent => nil, :label => "St. Eustatius", :search_label => nil, :sort => 230, :user_select => true},
    {:id =>"141", :parent => nil, :label => "St. John", :search_label => nil, :sort => 232, :user_select => true},
    {:id =>"142", :parent => nil, :label => "St. Kitts", :search_label => nil, :sort => 233, :user_select => true},
    {:id =>"143", :parent => nil, :label => "St. Lucia", :search_label => nil, :sort => 234, :user_select => true},
    {:id =>"144", :parent => nil, :label => "St. Maarten", :search_label => nil, :sort => 235, :user_select => true},
    {:id =>"145", :parent => nil, :label => "St. Thomas", :search_label => nil, :sort => 237, :user_select => true},
    {:id =>"146", :parent => nil, :label => "St. Vincent", :search_label => nil, :sort => 238, :user_select => true},
    {:id =>"147", :parent => nil, :label => "Saipan", :search_label => nil, :sort => 209, :user_select => true},
    {:id =>"148", :parent => nil, :label => "Saudi Arabia", :search_label => nil, :sort => 212, :user_select => true},
    {:id =>"149", :parent => nil, :label => "Scotland", :search_label => nil, :sort => 213, :user_select => true},
    {:id =>"150", :parent => nil, :label => "Senegal", :search_label => nil, :sort => 214, :user_select => true},
    {:id =>"151", :parent => nil, :label => "Seychelles", :search_label => nil, :sort => 216, :user_select => true},
    {:id =>"152", :parent => nil, :label => "Sierra Leone", :search_label => nil, :sort => 217, :user_select => true},
    {:id =>"153", :parent => nil, :label => "Singapore", :search_label => nil, :sort => 218, :user_select => true},
    {:id =>"154", :parent => nil, :label => "Somalia", :search_label => nil, :sort => 222, :user_select => true},
    {:id =>"155", :parent => nil, :label => "South Africa", :search_label => nil, :sort => 223, :user_select => true},
    {:id =>"156", :parent => nil, :label => "Spain", :search_label => nil, :sort => 224, :user_select => true},
    {:id =>"157", :parent => nil, :label => "Sri Lanka", :search_label => nil, :sort => 225, :user_select => true},
    {:id =>"158", :parent => nil, :label => "Sudan", :search_label => nil, :sort => 239, :user_select => true},
    {:id =>"159", :parent => nil, :label => "Suriname", :search_label => nil, :sort => 240, :user_select => true},
    {:id =>"160", :parent => nil, :label => "Swaziland", :search_label => nil, :sort => 242, :user_select => true},
    {:id =>"161", :parent => nil, :label => "Sweden", :search_label => nil, :sort => 243, :user_select => true},
    {:id =>"162", :parent => nil, :label => "Switzerland", :search_label => nil, :sort => 244, :user_select => true},
    {:id =>"163", :parent => nil, :label => "Syria", :search_label => nil, :sort => 245, :user_select => true},
    {:id =>"164", :parent => nil, :label => "Taiwan", :search_label => nil, :sort => 247, :user_select => true},
    {:id =>"165", :parent => nil, :label => "Tanzania", :search_label => nil, :sort => 249, :user_select => true},
    {:id =>"166", :parent => nil, :label => "Thailand", :search_label => nil, :sort => 250, :user_select => true},
    {:id =>"167", :parent => nil, :label => "Togo", :search_label => nil, :sort => 252, :user_select => true},
    {:id =>"168", :parent => nil, :label => "Trinidad and Tobago", :search_label => nil, :sort => 257, :user_select => true},
    {:id =>"169", :parent => nil, :label => "Tunisia", :search_label => nil, :sort => 259, :user_select => true},
    {:id =>"170", :parent => nil, :label => "Turkey", :search_label => nil, :sort => 260, :user_select => true},
    {:id =>"171", :parent => nil, :label => "Turks and Caicos Islands", :search_label => nil, :sort => 262, :user_select => true},
    {:id =>"172", :parent => nil, :label => "Uganda", :search_label => nil, :sort => 266, :user_select => true},
    {:id =>"173", :parent => nil, :label => "Ukraine", :search_label => nil, :sort => 267, :user_select => true},
    {:id =>"174", :parent => nil, :label => "United Arab Emirates", :search_label => nil, :sort => 269, :user_select => true},
    {:id =>"175", :parent => nil, :label => "U.S. Virgin Islands", :search_label => nil, :sort => 264, :user_select => true},
    {:id =>"176", :parent => nil, :label => "Uruguay", :search_label => nil, :sort => 270, :user_select => true},
    {:id =>"177", :parent => nil, :label => "Vatican City", :search_label => nil, :sort => 273, :user_select => true},
    {:id =>"178", :parent => nil, :label => "Venezuela", :search_label => nil, :sort => 274, :user_select => true},
    {:id =>"179", :parent => nil, :label => "Wales", :search_label => nil, :sort => 279, :user_select => true},
    {:id =>"180", :parent => nil, :label => "Yemen, Republic of", :search_label => nil, :sort => 284, :user_select => true},
    {:id =>"181", :parent => nil, :label => "Zaire", :search_label => nil, :sort => 286, :user_select => true},
    {:id =>"182", :parent => nil, :label => "Zambia", :search_label => nil, :sort => 287, :user_select => true},
    {:id =>"183", :parent => nil, :label => "Zimbabwe", :search_label => nil, :sort => 288, :user_select => true},
    {:id =>"184", :parent => nil, :label => "Albania", :search_label => nil, :sort => 3, :user_select => true},
    {:id =>"185", :parent => nil, :label => "Armenia", :search_label => nil, :sort => 13, :user_select => true},
    {:id =>"186", :parent => nil, :label => "Azerbaijan", :search_label => nil, :sort => 17, :user_select => true},
    {:id =>"187", :parent => nil, :label => "Azores", :search_label => nil, :sort => 18, :user_select => true},
    {:id =>"188", :parent => nil, :label => "Bosnia-Hercegovina", :search_label => nil, :sort => 32, :user_select => true},
    {:id =>"189", :parent => nil, :label => "Caicos Island", :search_label => nil, :sort => 42, :user_select => true},
    {:id =>"190", :parent => nil, :label => "Canary Islands", :search_label => nil, :sort => 46, :user_select => true},
    {:id =>"191", :parent => nil, :label => "Commonwealth of Ind State", :search_label => nil, :sort => 57, :user_select => true},
    {:id =>"192", :parent => nil, :label => "Cooper Island", :search_label => nil, :sort => 61, :user_select => true},
    {:id =>"193", :parent => nil, :label => "Cote D'Ivoire", :search_label => nil, :sort => 63, :user_select => true},
    {:id =>"194", :parent => nil, :label => "Croatia", :search_label => nil, :sort => 64, :user_select => true},
    {:id =>"195", :parent => nil, :label => "Haiti", :search_label => nil, :sort => 106, :user_select => true},
    {:id =>"196", :parent => nil, :label => "Iraq", :search_label => nil, :sort => 116, :user_select => true},
    {:id =>"197", :parent => nil, :label => "Isle of Man", :search_label => nil, :sort => 119, :user_select => true},
    {:id =>"198", :parent => nil, :label => "Jost Van Dyke Island", :search_label => nil, :sort => 126, :user_select => true},
    {:id =>"199", :parent => nil, :label => "Kazakhstan", :search_label => nil, :sort => 128, :user_select => true},
    {:id =>"200", :parent => nil, :label => "Kyrgyzstan", :search_label => nil, :sort => 135, :user_select => true},
    {:id =>"201", :parent => nil, :label => "Madeira Islands", :search_label => nil, :sort => 148, :user_select => true},
    {:id =>"202", :parent => nil, :label => "Malagasy", :search_label => nil, :sort => 149, :user_select => true},
    {:id =>"203", :parent => nil, :label => "Moldova", :search_label => nil, :sort => 162, :user_select => true},
    {:id =>"204", :parent => nil, :label => "Nevis", :search_label => nil, :sort => 173, :user_select => true},
    {:id =>"205", :parent => nil, :label => "Norman Island", :search_label => nil, :sort => 182, :user_select => true},
    {:id =>"206", :parent => nil, :label => "St. Christopher", :search_label => nil, :sort => 228, :user_select => true},
    {:id =>"207", :parent => nil, :label => "Serbia", :search_label => nil, :sort => 215, :user_select => true},
    {:id =>"208", :parent => nil, :label => "Slovakia", :search_label => nil, :sort => 219, :user_select => true},
    {:id =>"209", :parent => nil, :label => "Slovenia", :search_label => nil, :sort => 220, :user_select => true},
    {:id =>"210", :parent => nil, :label => "Solomon Islands", :search_label => nil, :sort => 221, :user_select => true},
    {:id =>"211", :parent => nil, :label => "Tajikistan", :search_label => nil, :sort => 248, :user_select => true},
    {:id =>"212", :parent => nil, :label => "Turkmenistan", :search_label => nil, :sort => 261, :user_select => true},
    {:id =>"213", :parent => nil, :label => "Yugoslavia", :search_label => nil, :sort => 285, :user_select => true},
    {:id =>"214", :parent => nil, :label => "USA", :search_label => nil, :sort => 1, :user_select => true},
    {:id =>"215", :parent => nil, :label => "Georgia", :search_label => nil, :sort => 93, :user_select => true},
    {:id =>"216", :parent => nil, :label => "Gibraltar", :search_label => nil, :sort => 96, :user_select => true},
    {:id =>"217", :parent => nil, :label => "Greenland", :search_label => nil, :sort => 98, :user_select => true},
    {:id =>"218", :parent => nil, :label => "Kampuchea", :search_label => nil, :sort => 127, :user_select => true},
    {:id =>"219", :parent => nil, :label => "Kiribati", :search_label => nil, :sort => 130, :user_select => true},
    {:id =>"220", :parent => nil, :label => "Laos", :search_label => nil, :sort => 136, :user_select => true},
    {:id =>"221", :parent => nil, :label => "Liberia", :search_label => nil, :sort => 140, :user_select => true},
    {:id =>"222", :parent => nil, :label => "Macedonia", :search_label => nil, :sort => 146, :user_select => true},
    {:id =>"223", :parent => nil, :label => "Mongolia", :search_label => nil, :sort => 164, :user_select => true},
    {:id =>"224", :parent => nil, :label => "Myanmar", :search_label => nil, :sort => 168, :user_select => true},
    {:id =>"225", :parent => nil, :label => "Nauru", :search_label => nil, :sort => 170, :user_select => true},
    {:id =>"226", :parent => nil, :label => "Niue", :search_label => nil, :sort => 180, :user_select => true},
    {:id =>"228", :parent => nil, :label => "San Marino", :search_label => nil, :sort => 210, :user_select => true},
    {:id =>"229", :parent => nil, :label => "Sao Tome", :search_label => nil, :sort => 211, :user_select => true},
    {:id =>"230", :parent => nil, :label => "Tonaga", :search_label => nil, :sort => 254, :user_select => true},
    {:id =>"231", :parent => nil, :label => "Tuvalu", :search_label => nil, :sort => 263, :user_select => true},
    {:id =>"232", :parent => nil, :label => "Uzbekistan", :search_label => nil, :sort => 271, :user_select => true},
    {:id =>"233", :parent => nil, :label => "Vanuatu", :search_label => nil, :sort => 272, :user_select => true},
    {:id =>"234", :parent => nil, :label => "Vietnam", :search_label => nil, :sort => 275, :user_select => true},
    {:id =>"235", :parent => nil, :label => "Virgin Islands (British)", :search_label => nil, :sort => 276, :user_select => true},
    {:id =>"236", :parent => nil, :label => "Virgin Islands (U.S.)", :search_label => nil, :sort => 277, :user_select => true},
    {:id =>"237", :parent => nil, :label => "Wake Island", :search_label => nil, :sort => 278, :user_select => true},
    {:id =>"238", :parent => nil, :label => "Western Samoa", :search_label => nil, :sort => 281, :user_select => true},
    {:id =>"239", :parent => nil, :label => "Korea", :search_label => nil, :sort => 131, :user_select => true},
    {:id =>"240", :parent => nil, :label => "American Samoa", :search_label => nil, :sort => 5, :user_select => true},
    {:id =>"241", :parent => nil, :label => "Andorra", :search_label => nil, :sort => 6, :user_select => true},
    {:id =>"242", :parent => nil, :label => "Cook Islands", :search_label => nil, :sort => 60, :user_select => true},
    {:id =>"243", :parent => nil, :label => "French Polynesia", :search_label => nil, :sort => 88, :user_select => true},
    {:id =>"244", :parent => nil, :label => "Holland", :search_label => nil, :sort => 108, :user_select => true},
    {:id =>"245", :parent => nil, :label => "St. Martin", :search_label => nil, :sort => 236, :user_select => true},
    {:id =>"246", :parent => nil, :label => "Nevis (St. Kitts)", :search_label => nil, :sort => 174, :user_select => true},
    {:id =>"247", :parent => nil, :label => "Tahiti", :search_label => nil, :sort => 246, :user_select => true},
    {:id =>"248", :parent => nil, :label => "Tinian", :search_label => nil, :sort => 251, :user_select => true},
    {:id =>"249", :parent => nil, :label => "Tonga", :search_label => nil, :sort => 255, :user_select => true},
    {:id =>"250", :parent => nil, :label => "Tortola", :search_label => nil, :sort => 256, :user_select => true},
    {:id =>"251", :parent => nil, :label => "Truk", :search_label => nil, :sort => 258, :user_select => true},
    {:id =>"252", :parent => nil, :label => "Union Island", :search_label => nil, :sort => 268, :user_select => true},
    {:id =>"253", :parent => nil, :label => "Wallis Island", :search_label => nil, :sort => 280, :user_select => true},
    {:id =>"254", :parent => nil, :label => "Futuna Island", :search_label => nil, :sort => 90, :user_select => true},
    {:id =>"255", :parent => nil, :label => "Yap", :search_label => nil, :sort => 283, :user_select => true},
    {:id =>"256", :parent => nil, :label => "Kosrae", :search_label => nil, :sort => 133, :user_select => true},
    {:id =>"257", :parent => nil, :label => "Northern Mariana Islands", :search_label => nil, :sort => 183, :user_select => true},
    {:id =>"258", :parent => nil, :label => "Norfolk Island", :search_label => nil, :sort => 181, :user_select => true},
    {:id =>"260", :parent => nil, :label => "Ponape", :search_label => nil, :sort => 196, :user_select => true},
    {:id =>"261", :parent => nil, :label => "Rota", :search_label => nil, :sort => 202, :user_select => true},
    {:id =>"262", :parent => nil, :label => "Puerto Rico", :search_label => nil, :sort => 198, :user_select => true},
    {:id =>"263", :parent => nil, :label => "Afghanistan", :search_label => nil, :sort => 2, :user_select => true},
    {:id =>"264", :parent => nil, :label => "Antartica", :search_label => nil, :sort => 9, :user_select => true},
    {:id =>"265", :parent => nil, :label => "Bouvet Island", :search_label => nil, :sort => 34, :user_select => true},
    {:id =>"266", :parent => nil, :label => "British Indian Ocean Territory", :search_label => nil, :sort => 37, :user_select => true},
    {:id =>"277", :parent => nil, :label => "Cambodia", :search_label => nil, :sort => 43, :user_select => true},
    {:id =>"278", :parent => nil, :label => "Christmas Island", :search_label => nil, :sort => 54, :user_select => true},
    {:id =>"279", :parent => nil, :label => "Cocos (Keeling) Islands", :search_label => nil, :sort => 55, :user_select => true},
    {:id =>"280", :parent => nil, :label => "Comoros", :search_label => nil, :sort => 58, :user_select => true},
    {:id =>"281", :parent => nil, :label => "Cuba", :search_label => nil, :sort => 65, :user_select => true},
    {:id =>"282", :parent => nil, :label => "East Timor", :search_label => nil, :sort => 73, :user_select => true},
    {:id =>"283", :parent => nil, :label => "Eritrea", :search_label => nil, :sort => 79, :user_select => true},
    {:id =>"284", :parent => nil, :label => "Falkland Islands", :search_label => nil, :sort => 82, :user_select => true},
    {:id =>"285", :parent => nil, :label => "Faroe Islands", :search_label => nil, :sort => 83, :user_select => true},
    {:id =>"286", :parent => nil, :label => "French Southern Territories", :search_label => nil, :sort => 89, :user_select => true},
    {:id =>"287", :parent => nil, :label => "Heard and McDonald Islands", :search_label => nil, :sort => 107, :user_select => true},
    {:id =>"288", :parent => nil, :label => "Libya", :search_label => nil, :sort => 141, :user_select => true},
    {:id =>"289", :parent => nil, :label => "Mayotte", :search_label => nil, :sort => 159, :user_select => true},
    {:id =>"290", :parent => nil, :label => "Pitcairn Island", :search_label => nil, :sort => 194, :user_select => true},
    {:id =>"291", :parent => nil, :label => "S. Georgia & S. Sandwich Islan", :search_label => nil, :sort => 205, :user_select => true},
    {:id =>"292", :parent => nil, :label => "St. Helena", :search_label => nil, :sort => 231, :user_select => true},
    {:id =>"293", :parent => nil, :label => "Saint Pierre and Miquelon", :search_label => nil, :sort => 207, :user_select => true},
    {:id =>"294", :parent => nil, :label => "Saint Tome and Principe", :search_label => nil, :sort => 208, :user_select => true},
    {:id =>"295", :parent => nil, :label => "Svalbard and Jan Mayen Islands", :search_label => nil, :sort => 241, :user_select => true},
    {:id =>"296", :parent => nil, :label => "Tokelau", :search_label => nil, :sort => 253, :user_select => true},
    {:id =>"297", :parent => nil, :label => "USA Minor Outlying Islands", :search_label => nil, :sort => 265, :user_select => true}
  ]
  
  
  STATE_APO = [
    {:id => "0", :parent => nil, :label => "UNSPECIFIED", :search_label => nil, :sort =>  62, :user_select => false},  
    {:id => "AK", :parent => nil, :label => "Alaska", :search_label => nil, :sort =>  1, :user_select => true},  
    {:id => "AL", :parent => nil, :label => "Alabama", :search_label => nil, :sort =>  2, :user_select => true},  
    {:id => "APOAA", :parent => nil, :label => "APO AA", :search_label => nil, :sort =>  56, :user_select => true},  
    {:id => "APOAE", :parent => nil, :label => "APO AE", :search_label => nil, :sort =>  57, :user_select => true},  
    {:id => "APOAP", :parent => nil, :label => "APO AP", :search_label => nil, :sort =>  58, :user_select => true},  
    {:id => "AR", :parent => nil, :label => "Arkansas", :search_label => nil, :sort =>  3, :user_select => true},  
    {:id => "AZ", :parent => nil, :label => "Arizona", :search_label => nil, :sort =>  4, :user_select => true},  
    {:id => "CA", :parent => nil, :label => "California", :search_label => nil, :sort =>  5, :user_select => true},  
    {:id => "CO", :parent => nil, :label => "Colorado", :search_label => nil, :sort =>  6, :user_select => true},  
    {:id => "CT", :parent => nil, :label => "Connecticut", :search_label => nil, :sort =>  7, :user_select => true},  
    {:id => "DC", :parent => nil, :label => "District of Columbia", :search_label => nil, :sort =>  8, :user_select => true},  
    {:id => "DE", :parent => nil, :label => "Delaware", :search_label => nil, :sort =>  9, :user_select => true},  
    {:id => "FL", :parent => nil, :label => "Florida", :search_label => nil, :sort =>  10, :user_select => true},  
    {:id => "FPOAA", :parent => nil, :label => "FPO AA", :search_label => nil, :sort =>  59, :user_select => true},  
    {:id => "FPOAE", :parent => nil, :label => "FPO AE", :search_label => nil, :sort =>  60, :user_select => true},  
    {:id => "FPOAP", :parent => nil, :label => "FPO AP", :search_label => nil, :sort =>  61, :user_select => true},  
    {:id => "GA", :parent => nil, :label => "Georgia", :search_label => nil, :sort =>  11, :user_select => true},  
    {:id => "GUAM", :parent => nil, :label => "Guam", :search_label => nil, :sort =>  12, :user_select => true},  
    {:id => "HI", :parent => nil, :label => "Hawaii", :search_label => nil, :sort =>  13, :user_select => true},  
    {:id => "IA", :parent => nil, :label => "Iowa", :search_label => nil, :sort =>  14, :user_select => true},  
    {:id => "ID", :parent => nil, :label => "Idaho", :search_label => nil, :sort =>  15, :user_select => true},  
    {:id => "IL", :parent => nil, :label => "Illinois", :search_label => nil, :sort =>  16, :user_select => true},  
    {:id => "IN", :parent => nil, :label => "Indiana", :search_label => nil, :sort =>  17, :user_select => true},  
    {:id => "KS", :parent => nil, :label => "Kansas", :search_label => nil, :sort =>  18, :user_select => true},  
    {:id => "KY", :parent => nil, :label => "Kentucky", :search_label => nil, :sort =>  19, :user_select => true},  
    {:id => "LA", :parent => nil, :label => "Louisiana", :search_label => nil, :sort =>  20, :user_select => true},  
    {:id => "MA", :parent => nil, :label => "Massachusetts", :search_label => nil, :sort =>  21, :user_select => true},  
    {:id => "MD", :parent => nil, :label => "Maryland", :search_label => nil, :sort =>  22, :user_select => true},  
    {:id => "ME", :parent => nil, :label => "Maine", :search_label => nil, :sort =>  23, :user_select => true},  
    {:id => "MI", :parent => nil, :label => "Michigan", :search_label => nil, :sort =>  24, :user_select => true},  
    {:id => "MN", :parent => nil, :label => "Minnesota", :search_label => nil, :sort =>  25, :user_select => true},  
    {:id => "MO", :parent => nil, :label => "Missouri", :search_label => nil, :sort =>  26, :user_select => true},  
    {:id => "MS", :parent => nil, :label => "Mississippi", :search_label => nil, :sort =>  27, :user_select => true},  
    {:id => "MT", :parent => nil, :label => "Montana", :search_label => nil, :sort =>  28, :user_select => true},  
    {:id => "NC", :parent => nil, :label => "North Carolina", :search_label => nil, :sort =>  29, :user_select => true},  
    {:id => "ND", :parent => nil, :label => "North Dakota", :search_label => nil, :sort =>  30, :user_select => true},  
    {:id => "NE", :parent => nil, :label => "Nebraska", :search_label => nil, :sort =>  31, :user_select => true},  
    {:id => "NH", :parent => nil, :label => "New Hampshire", :search_label => nil, :sort =>  32, :user_select => true},  
    {:id => "NJ", :parent => nil, :label => "New Jersey", :search_label => nil, :sort =>  33, :user_select => true},  
    {:id => "NM", :parent => nil, :label => "New Mexico", :search_label => nil, :sort =>  34, :user_select => true},  
    {:id => "NV", :parent => nil, :label => "Nevada", :search_label => nil, :sort =>  35, :user_select => true},  
    {:id => "NY", :parent => nil, :label => "New York", :search_label => nil, :sort =>  36, :user_select => true},  
    {:id => "OH", :parent => nil, :label => "Ohio", :search_label => nil, :sort =>  37, :user_select => true},  
    {:id => "OK", :parent => nil, :label => "Oklahoma", :search_label => nil, :sort =>  38, :user_select => true},  
    {:id => "OR", :parent => nil, :label => "Oregon", :search_label => nil, :sort =>  39, :user_select => true},  
    {:id => "PA", :parent => nil, :label => "Pennsylvania", :search_label => nil, :sort =>  40, :user_select => true},  
    {:id => "PRICO", :parent => nil, :label => "Puerto Rico", :search_label => nil, :sort =>  41, :user_select => true},  
    {:id => "RI", :parent => nil, :label => "Rhode Island", :search_label => nil, :sort =>  42, :user_select => true},  
    {:id => "SC", :parent => nil, :label => "South Carolina", :search_label => nil, :sort =>  44, :user_select => true},  
    {:id => "SD", :parent => nil, :label => "South Dakota", :search_label => nil, :sort =>  45, :user_select => true},  
    {:id => "SOMOA", :parent => nil, :label => "Somoa", :search_label => nil, :sort =>  43, :user_select => true},  
    {:id => "TN", :parent => nil, :label => "Tennessee", :search_label => nil, :sort =>  46, :user_select => true},  
    {:id => "TX", :parent => nil, :label => "Texas", :search_label => nil, :sort =>  47, :user_select => true},  
    {:id => "USVI", :parent => nil, :label => "US Virgin Islands", :search_label => nil, :sort =>  48, :user_select => true},  
    {:id => "UT", :parent => nil, :label => "Utah", :search_label => nil, :sort =>  49, :user_select => true},  
    {:id => "VA", :parent => nil, :label => "Virginia", :search_label => nil, :sort =>  50, :user_select => true},  
    {:id => "VT", :parent => nil, :label => "Vermont", :search_label => nil, :sort =>  51, :user_select => true},  
    {:id => "WA", :parent => nil, :label => "Washington", :search_label => nil, :sort =>  52, :user_select => true},  
    {:id => "WI", :parent => nil, :label => "Wisconsin", :search_label => nil, :sort =>  53, :user_select => true},  
    {:id => "WV", :parent => nil, :label => "West Virginia", :search_label => nil, :sort =>  54, :user_select => true},  
    {:id => "WY", :parent => nil, :label => "Wyoming", :search_label => nil, :sort =>  55, :user_select => true}
  ]
  

  
end
